<a href="https://colab.research.google.com/github/Yogeswari-sri/Pythoncourse_Fundamentals/blob/main/Student_Performance_Analysis_Using_NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Case Study: Student Performance Analysis Using NumPy

A school wants to analyze the marks of students in 5 subjects using NumPy.

You need to:

Store student marks using NumPy arrays

Calculate:

Total marks, Average marks, Highest marks, Lowest marks,Percentage

Find:

Students who scored above average, Students who failed, Subject-wise average

In [56]:
# STUDENT PERFORMANCE ANALYSIS USING NUMPY

# Import NumPy library
import numpy as np

marks = np.array([
    [100, 89, 76, 89,97],   # Student A
    [78, 85, 90, 88, 76],   # Student B
    [65, 70, 60, 72, 68],   # Student C
    [90, 92, 88, 95, 91],   # Student D
    [45, 50, 55, 48, 52],   # Student E

])

students=np.array(["A","B","C","D","E"])
print(students)


print("--------- STUDENT MARKS --------\n")
print(marks)

total_marks=np.sum(marks,axis=1)
print("Total marks are : ",total_marks)

Average = np.mean(marks,axis=1)
print("Average  : ",Average)

max_marks=np.max(marks,axis=1)
print("Maximum marks ", max_marks)

min_marks=np.min(marks,axis=1)
print("Minimum marks ", min_marks)

percentage=(total_marks/500)*100
percentage

overall_average = np.mean(total_marks)
print("Overall_Average " ,overall_average)

student_above_average=students[total_marks > overall_average]
print("Student above average marks ",student_above_average)

failed_students=students[np.any(marks < 50,axis=1)]
print("failed students  below 50 : ",failed_students)

subject_average=np.mean(marks,axis=0)
print("Subject average :",subject_average)

# Display Student-wise Report

print("\n========== STUDENT REPORT ==========")

for i in range(len(students)):

    print("\nStudent Name :", students[i])

    print("Marks :", marks[i])

    print("Total Marks :", total_marks[i])

    print("Average Marks :", Average[i])

    print("Highest Mark :", max_marks[i])

    print("Lowest Mark :", min_marks[i])

    print("Percentage :", percentage[i])


# Rank Students Based on Total Marks
# argsort() sorts in ascending order
# [::-1] converts to descending order

ranking = np.argsort(total_marks)[::-1]     #index wise sorting

print("\n========== STUDENT RANKING ==========")

for rank, index in enumerate(ranking, start=1):

    print(f"Rank {rank} : Student {students[index]}) "
    f"-> Total Marks = {total_marks[index]}")





['A' 'B' 'C' 'D' 'E']
--------- STUDENT MARKS --------

[[100  89  76  89  97]
 [ 78  85  90  88  76]
 [ 65  70  60  72  68]
 [ 90  92  88  95  91]
 [ 45  50  55  48  52]]
Total marks are :  [451 417 335 456 250]
Average  :  [90.2 83.4 67.  91.2 50. ]
Maximum marks  [100  90  72  95  55]
Minimum marks  [76 76 60 88 45]
Overall_Average  381.8
Student above average marks  ['A' 'B' 'D']
failed students  below 50 :  ['E']
Subject average : [75.6 77.2 73.8 78.4 76.8]

========== STUDENT REPORT ==========

Student Name : A
Marks : [100  89  76  89  97]
Total Marks : 451
Average Marks : 90.2
Highest Mark : 100
Lowest Mark : 76
Percentage : 90.2

Student Name : B
Marks : [78 85 90 88 76]
Total Marks : 417
Average Marks : 83.4
Highest Mark : 90
Lowest Mark : 76
Percentage : 83.39999999999999

Student Name : C
Marks : [65 70 60 72 68]
Total Marks : 335
Average Marks : 67.0
Highest Mark : 72
Lowest Mark : 60
Percentage : 67.0

Student Name : D
Marks : [90 92 88 95 91]
Total Marks : 456
Average Ma